/*
 * generated by Xtext 2.32.0
 */
package fr.l127.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.l127.ide.contentassist.antlr.internal.InternalLAParser;
import fr.l127.services.LAGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LAParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LAGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LAGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getLibrairieAccess().getGroup(), "rule__Librairie__Group__0");
			builder.put(grammarAccess.getAlgorithmeAccess().getGroup(), "rule__Algorithme__Group__0");
			builder.put(grammarAccess.getLibrairieAccess().getNameAssignment_1(), "rule__Librairie__NameAssignment_1");
			builder.put(grammarAccess.getLibrairieAccess().getElementsAssignment_3(), "rule__Librairie__ElementsAssignment_3");
			builder.put(grammarAccess.getAlgorithmeAccess().getNameAssignment_1(), "rule__Algorithme__NameAssignment_1");
			builder.put(grammarAccess.getAlgorithmeAccess().getEntreesAssignment_5(), "rule__Algorithme__EntreesAssignment_5");
			builder.put(grammarAccess.getAlgorithmeAccess().getSortiesAssignment_9(), "rule__Algorithme__SortiesAssignment_9");
			builder.put(grammarAccess.getAlgorithmeAccess().getCheminAssignment_12(), "rule__Algorithme__CheminAssignment_12");
			builder.put(grammarAccess.getEntreeAccess().getIdColonneAssignment(), "rule__Entree__IdColonneAssignment");
			builder.put(grammarAccess.getSortieAccess().getIdColonneAssignment(), "rule__Sortie__IdColonneAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LAGrammarAccess grammarAccess;

	@Override
	protected InternalLAParser createParser() {
		InternalLAParser result = new InternalLAParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LAGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LAGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
