<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithme" nsURI="http://www.example.org/algorithme" nsPrefix="algorithme">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entrees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sorties" eType="ecore:EClass ../../fr.l127.schemaTable/model/schemaTable.ecore#//Colonne"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entrées" upperBound="-1"
        eType="ecore:EClass ../../fr.l127.schemaTable/model/schemaTable.ecore#//Colonne"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressource" eType="#//Ressource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ressource" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithme" eType="#//Algorithme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fichier" eSuperTypes="#//Ressource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chemin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
