/*
 * generated by Xtext 2.32.0
 */
package fr.l127.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLAScopeProvider extends DelegatingScopeProvider {
}
