/*
 * generated by Xtext 2.32.0
 */
package fr.l127.serializer;

import com.google.inject.Inject;
import fr.l127.lA.Algorithme;
import fr.l127.lA.LAPackage;
import fr.l127.lA.Librairie;
import fr.l127.services.LAGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class LASemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LAGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == LAPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LAPackage.ALGORITHME:
				sequence_Algorithme(context, (Algorithme) semanticObject); 
				return; 
			case LAPackage.LIBRAIRIE:
				sequence_Librairie(context, (Librairie) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     LibrairieElement returns Algorithme
	 *     Algorithme returns Algorithme
	 *
	 * Constraint:
	 *     (name=ID entrees+=ID+ sorties+=ID+ chemin=ID)
	 * </pre>
	 */
	protected void sequence_Algorithme(ISerializationContext context, Algorithme semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Librairie returns Librairie
	 *
	 * Constraint:
	 *     (name=ID elements+=LibrairieElement*)
	 * </pre>
	 */
	protected void sequence_Librairie(ISerializationContext context, Librairie semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
