/*
 * generated by Xtext 2.32.0
 */
package fr.l127.ui;

import com.google.inject.Injector;
import fr.l127.librairieAlgorithme.ui.internal.LibrairieAlgorithmeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LibrairieAlgorithmeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LibrairieAlgorithmeActivator activator = LibrairieAlgorithmeActivator.getInstance();
		return activator != null ? activator.getInjector(LibrairieAlgorithmeActivator.FR_L127_LA) : null;
	}

}
