/**
 * generated by Xtext 2.32.0
 */
package fr.l127.lA;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithme</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.l127.lA.Algorithme#getName <em>Name</em>}</li>
 *   <li>{@link fr.l127.lA.Algorithme#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link fr.l127.lA.Algorithme#getSorties <em>Sorties</em>}</li>
 *   <li>{@link fr.l127.lA.Algorithme#getChemin <em>Chemin</em>}</li>
 * </ul>
 *
 * @see fr.l127.lA.LAPackage#getAlgorithme()
 * @model
 * @generated
 */
public interface Algorithme extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.l127.lA.LAPackage#getAlgorithme_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.l127.lA.Algorithme#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entrees</b></em>' containment reference list.
   * The list contents are of type {@link fr.l127.lA.Entree}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entrees</em>' containment reference list.
   * @see fr.l127.lA.LAPackage#getAlgorithme_Entrees()
   * @model containment="true"
   * @generated
   */
  EList<Entree> getEntrees();

  /**
   * Returns the value of the '<em><b>Sorties</b></em>' containment reference list.
   * The list contents are of type {@link fr.l127.lA.Sortie}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sorties</em>' containment reference list.
   * @see fr.l127.lA.LAPackage#getAlgorithme_Sorties()
   * @model containment="true"
   * @generated
   */
  EList<Sortie> getSorties();

  /**
   * Returns the value of the '<em><b>Chemin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chemin</em>' attribute.
   * @see #setChemin(String)
   * @see fr.l127.lA.LAPackage#getAlgorithme_Chemin()
   * @model
   * @generated
   */
  String getChemin();

  /**
   * Sets the value of the '{@link fr.l127.lA.Algorithme#getChemin <em>Chemin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chemin</em>' attribute.
   * @see #getChemin()
   * @generated
   */
  void setChemin(String value);

} // Algorithme
