/**
 * generated by Xtext 2.32.0
 */
package fr.l127.lA;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.l127.lA.LAPackage
 * @generated
 */
public interface LAFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LAFactory eINSTANCE = fr.l127.lA.impl.LAFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Librairie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Librairie</em>'.
   * @generated
   */
  Librairie createLibrairie();

  /**
   * Returns a new object of class '<em>Librairie Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Librairie Element</em>'.
   * @generated
   */
  LibrairieElement createLibrairieElement();

  /**
   * Returns a new object of class '<em>Algorithme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithme</em>'.
   * @generated
   */
  Algorithme createAlgorithme();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LAPackage getLAPackage();

} //LAFactory
