/**
 * generated by Xtext 2.32.0
 */
package fr.l127.lA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Librairie Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.l127.lA.LAPackage#getLibrairieElement()
 * @model
 * @generated
 */
public interface LibrairieElement extends EObject
{
} // LibrairieElement
