/**
 * generated by Xtext 2.32.0
 */
package fr.l127.lA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sortie</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.l127.lA.Sortie#getIdColonne <em>Id Colonne</em>}</li>
 * </ul>
 *
 * @see fr.l127.lA.LAPackage#getSortie()
 * @model
 * @generated
 */
public interface Sortie extends EObject
{
  /**
   * Returns the value of the '<em><b>Id Colonne</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id Colonne</em>' attribute.
   * @see #setIdColonne(int)
   * @see fr.l127.lA.LAPackage#getSortie_IdColonne()
   * @model
   * @generated
   */
  int getIdColonne();

  /**
   * Sets the value of the '{@link fr.l127.lA.Sortie#getIdColonne <em>Id Colonne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id Colonne</em>' attribute.
   * @see #getIdColonne()
   * @generated
   */
  void setIdColonne(int value);

} // Sortie
