/**
 * generated by Xtext 2.32.0
 */
package fr.l127.lA.impl;

import fr.l127.lA.Algorithme;
import fr.l127.lA.LAPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Algorithme</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.l127.lA.impl.AlgorithmeImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.l127.lA.impl.AlgorithmeImpl#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link fr.l127.lA.impl.AlgorithmeImpl#getSorties <em>Sorties</em>}</li>
 *   <li>{@link fr.l127.lA.impl.AlgorithmeImpl#getChemin <em>Chemin</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AlgorithmeImpl extends LibrairieElementImpl implements Algorithme
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEntrees() <em>Entrees</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntrees()
   * @generated
   * @ordered
   */
  protected EList<String> entrees;

  /**
   * The cached value of the '{@link #getSorties() <em>Sorties</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSorties()
   * @generated
   * @ordered
   */
  protected EList<String> sorties;

  /**
   * The default value of the '{@link #getChemin() <em>Chemin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChemin()
   * @generated
   * @ordered
   */
  protected static final String CHEMIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getChemin() <em>Chemin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChemin()
   * @generated
   * @ordered
   */
  protected String chemin = CHEMIN_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AlgorithmeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LAPackage.Literals.ALGORITHME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LAPackage.ALGORITHME__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getEntrees()
  {
    if (entrees == null)
    {
      entrees = new EDataTypeEList<String>(String.class, this, LAPackage.ALGORITHME__ENTREES);
    }
    return entrees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getSorties()
  {
    if (sorties == null)
    {
      sorties = new EDataTypeEList<String>(String.class, this, LAPackage.ALGORITHME__SORTIES);
    }
    return sorties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getChemin()
  {
    return chemin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChemin(String newChemin)
  {
    String oldChemin = chemin;
    chemin = newChemin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LAPackage.ALGORITHME__CHEMIN, oldChemin, chemin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LAPackage.ALGORITHME__NAME:
        return getName();
      case LAPackage.ALGORITHME__ENTREES:
        return getEntrees();
      case LAPackage.ALGORITHME__SORTIES:
        return getSorties();
      case LAPackage.ALGORITHME__CHEMIN:
        return getChemin();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LAPackage.ALGORITHME__NAME:
        setName((String)newValue);
        return;
      case LAPackage.ALGORITHME__ENTREES:
        getEntrees().clear();
        getEntrees().addAll((Collection<? extends String>)newValue);
        return;
      case LAPackage.ALGORITHME__SORTIES:
        getSorties().clear();
        getSorties().addAll((Collection<? extends String>)newValue);
        return;
      case LAPackage.ALGORITHME__CHEMIN:
        setChemin((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LAPackage.ALGORITHME__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LAPackage.ALGORITHME__ENTREES:
        getEntrees().clear();
        return;
      case LAPackage.ALGORITHME__SORTIES:
        getSorties().clear();
        return;
      case LAPackage.ALGORITHME__CHEMIN:
        setChemin(CHEMIN_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LAPackage.ALGORITHME__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LAPackage.ALGORITHME__ENTREES:
        return entrees != null && !entrees.isEmpty();
      case LAPackage.ALGORITHME__SORTIES:
        return sorties != null && !sorties.isEmpty();
      case LAPackage.ALGORITHME__CHEMIN:
        return CHEMIN_EDEFAULT == null ? chemin != null : !CHEMIN_EDEFAULT.equals(chemin);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", entrees: ");
    result.append(entrees);
    result.append(", sorties: ");
    result.append(sorties);
    result.append(", chemin: ");
    result.append(chemin);
    result.append(')');
    return result.toString();
  }

} //AlgorithmeImpl
