/**
 * generated by Xtext 2.32.0
 */
package fr.l127.lA.impl;

import fr.l127.lA.LAPackage;
import fr.l127.lA.LibrairieElement;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Librairie Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LibrairieElementImpl extends MinimalEObjectImpl.Container implements LibrairieElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LibrairieElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LAPackage.Literals.LIBRAIRIE_ELEMENT;
  }

} //LibrairieElementImpl
