<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ressourceGraphique" nsURI="http://www.example.org/ressourceGraphique"
    nsPrefix="ressourceGraphique">
  <eClassifiers xsi:type="ecore:EClass" name="RessourceGraphique">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bloc" eType="#//Bloc" eOpposite="#//Bloc/ressourcegraphique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressourcegraphique" eType="#//RessourceGraphique"
        eOpposite="#//RessourceGraphique/bloc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entree" upperBound="-1"
        eType="#//Bloc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortie" eType="#//Bloc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fonction" eSuperTypes="#//Bloc"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fichier" eSuperTypes="#//Bloc"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constante" eSuperTypes="#//Bloc"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefColonne" eSuperTypes="#//Bloc"/>
</ecore:EPackage>
