/*
 * generated by Xtext 2.32.0
 */
package fr.l127.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LAUiModule extends AbstractLAUiModule {

	public LAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
