/*
 * generated by Xtext 2.32.0
 */
package fr.l127.ui.tests;

import com.google.inject.Injector;
import fr.l127.librairieAlgorithme.ui.internal.LibrairieAlgorithmeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LAUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LibrairieAlgorithmeActivator.getInstance().getInjector("fr.l127.LA");
	}

}
