/**
 * generated by Xtext 2.32.0
 */
package fr.l127.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(LAInjectorProvider.class)
@SuppressWarnings("all")
public class LAParsingTest {
  @Inject
  private /* ParseHelper<Librairie> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field LAParsingTest.parseHelper refers to the missing type Librairie"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
